/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_final_progra;

/**
 *
 * @author Joel Cartuche
 */
public class ventanaPrimcipal extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventanaPrimcipal() {
        initComponents();
        horasSemanales.setVisible(false);
        labelIngrese.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tiempoParcial = new javax.swing.JRadioButton();
        tiempoCompleto = new javax.swing.JRadioButton();
        tiempoMedio = new javax.swing.JRadioButton();
        nombres = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        horasClase = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        carrera = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horasSemanales = new javax.swing.JFormattedTextField();
        labelIngrese = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        primario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("profesores:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setText("cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("horas clase:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setText("carrera:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        buttonGroup1.add(tiempoParcial);
        tiempoParcial.setText("tiempo parcial");
        tiempoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoParcialActionPerformed(evt);
            }
        });
        tiempoParcial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tiempoParcialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tiempoParcialKeyReleased(evt);
            }
        });
        getContentPane().add(tiempoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        buttonGroup1.add(tiempoCompleto);
        tiempoCompleto.setText("tiempo completo");
        tiempoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoCompletoActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        buttonGroup1.add(tiempoMedio);
        tiempoMedio.setText("tiempo medio");
        tiempoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoMedioActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, -1));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 220, -1));
        getContentPane().add(horasClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, -1));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, -1));
        getContentPane().add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 220, -1));

        jLabel7.setText("tipo profesor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        getContentPane().add(horasSemanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 150, -1));

        labelIngrese.setText("Ingrese numero de horas semanales");
        getContentPane().add(labelIngrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jButton2.setText("agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jButton3.setText("visualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jButton4.setText("editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        jButton5.setText("vizulaisar por apellido");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        getContentPane().add(primario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 496));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiempoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoCompletoActionPerformed
horasSemanales.setVisible(false);
           labelIngrese.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoCompletoActionPerformed

    private void tiempoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoMedioActionPerformed
horasSemanales.setVisible(false);
           labelIngrese.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoMedioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tiempoParcialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiempoParcialKeyPressed
             // TODO add your handling code here:
    }//GEN-LAST:event_tiempoParcialKeyPressed

    private void tiempoParcialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiempoParcialKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoParcialKeyReleased

    private void tiempoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoParcialActionPerformed
       if(tiempoParcial.isSelected()){
           horasSemanales.setVisible(true);
        labelIngrese.setVisible(true);
       }
        
        
           // TODO add your handling code here:
    }//GEN-LAST:event_tiempoParcialActionPerformed

    ProfesorTiempoParcial profparcial = new ProfesorTiempoParcial();
    ProfesorTiempoCompleto profcompleto = new ProfesorTiempoCompleto();
    ProfesorMedioTiempo profmedio = new ProfesorMedioTiempo();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Profesores prof = new Profesores();
            Lista_profesores controlador = new Lista_profesores();
            String n="";
            if(tiempoParcial.isSelected()){
                profparcial = new ProfesorTiempoParcial();
                profparcial.setHorasSemanales(Integer.parseInt(horasSemanales.getText()));
                prof.horasComplementarias(profparcial);
               n="tiempoParcial";
            }
            if(tiempoCompleto.isSelected()){
                profcompleto = new ProfesorTiempoCompleto();
               prof.horasComplementarias(profcompleto);
               n= "tiempoCompleto";
               
            }
            if(tiempoMedio.isSelected()){
                profmedio = new ProfesorMedioTiempo();
                prof.horasComplementarias(profmedio);
                n="tiempoMedio";
            }
            prof= new Profesores(cedula.getText(), nombres.getText(), apellido.getText(), Integer.parseInt(horasClase.getText()), carrera.getText(), n);
            controlador.grabar(prof);
            
            
            
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       visualizar visualizar = new  visualizar();
        visualizar.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           nombres.setEnabled(false);
           apellido.setEnabled(false);
           horasClase.setEnabled(false);
           carrera.setEnabled(false);
           
           
           
           
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      visualizarApellido va = new  visualizarApellido();
        va.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrimcipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrimcipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carrera;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField horasClase;
    private javax.swing.JFormattedTextField horasSemanales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelIngrese;
    private javax.swing.JTextField nombres;
    private javax.swing.JLabel primario;
    private javax.swing.JRadioButton tiempoCompleto;
    private javax.swing.JRadioButton tiempoMedio;
    private javax.swing.JRadioButton tiempoParcial;
    // End of variables declaration//GEN-END:variables
}
